### ISSUE TITLE
Update content in Platforms > The Landscape page

### ISSUE THREAD

**Issue by Lucrezia-Cester** [GSTT-CSC/csc-test-site#1]
In the Miro design, under platforms is supposed to be a page called landscape where there is going to be an interactive diagram of various projects, each of which will be accessed by clicking on the image icon with which it will be represented. I will write down the lay out for this page.

**Comment by tomaroberts** [comment]
Suggest changing page title from "The Landscape" to something else. Also, this is currently the only page under the Platforms tab. What else do we need?

**Comment by tomaroberts** [comment]
Partially resolved by #81

**Comment by tomaroberts** [comment]
Mostly resolved by #64 – bugfix required, transferred to issue #89
