### ISSUE TITLE
Add content to Handbook page

### ISSUE THREAD

**Issue by Lucrezia-Cester** [GSTT-CSC/csc-test-site#10]

**Comment by tomaroberts** [comment]
Hi Lu, I think I'll tackle this one if that's okay. Have a few ideas for this.

**Comment by tomaroberts** [comment]
Essential part of site, but not a requirement for MVP so going to remove Deployment Requirement tag. Will prioritise further down line.

**Comment by tomaroberts** [comment]
Started this in branch `handbook`. Currently looks like this:

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/15610752/168650974-aaff97c9-5c68-4879-9b27-b1418a94d621.png">

Implements [ScrollSpy](https://getbootstrap.com/docs/5.2/components/scrollspy/) where the left-hand contents box moves as you scroll.

I've put in a few initial sections, but this is intended to be very comprehensive. Will assign someone else to begin creating the entries.

**Comment by tomaroberts** [comment]
The Handbook will grow and grow as we go forward. For MVP, we need barebones amount of sections. Feel free to choose whatever you think are essential sections to have!

**Comment by tomaroberts** [comment]
I'm going to close this issue for the purposes of MVP. It will grow and grow, but we have a really great start now – see #76
