### ISSUE TITLE
Add Kavitha to Team page

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#102]
Follow-up from #20 

Add Kavitha to Team page and created a bio.

This is already underway in two PRs: https://github.com/GSTT-CSC/csc-test-site/pull/95 and https://github.com/GSTT-CSC/csc-test-site/pull/100.

**Comment by kavithavaran** [comment]
Hi Tom, 

I think I have written my bio and added a picture.

**Comment by lucy-funnell** [comment]
Hi Tom, I've noticed some of the team members have both their First Name and Surname, while other have just their First Name. Shall we format it, so everyones profile is the same?

**Comment by tomaroberts** [comment]
@lucy-funnell – good spot. Agree.

**Comment by tomaroberts** [comment]
Resolved by #104
