### ISSUE TITLE
Automatically archive old calendar events

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#110]
Ported from here: https://github.com/GSTT-CSC/gstt-csc-old/issues/88

> Unless someone manually reviews it on a regular basis, it will start to look dated and therefore sloppy if past events remain. Some css to order by date and remove if date is in the past should do the trick.

**Comment by Lucrezia-Cester** [comment]
Jekyll is a static site so this will be slightly tricky but I'll see if there is any way to get this done

**Comment by AnilMistry** [comment]
Could be a github action to update the wesbite weekly?
A python script that ingests the yaml file, parses into a pandas dataframe, removes items based on data, then re-generates the yaml file.

**Comment by dangerdika** [comment]
No longer relevant as the calendar feature has been removed
