### ISSUE TITLE
Add SOPs and Guides to the Handbook

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/csc-test-site#115]
Migrate the old (and new!) write ups of SOPs so they're accessible on the website

**Comment by heyhaleema** [comment]
@dangerdika @tomaroberts What do you think of creating a new section under About Us, e.g. "GUIDES"? I was thinking it could be in the Handbook, but it'll likely become long and require quite a bit of scrolling. I'm happy to take a first crack at this issue if that sounds like a reasonable start.

**Comment by dangerdika** [comment]
@heyhaleema  I think it should be in the handbook and have a section on guides as well as a section for SOPs. We need a good menu for the handbook I agree but there will inevitably be a lot of content there anyway

**Comment by dangerdika** [comment]
@heyhaleema I've changed my mind, I think you're right - just had another look and your solution is much better and clearer, yes we should do another section for SOPs/Guides (I vote call the section SOP tho)
