### ISSUE TITLE
add some of these MONAI events to website

### ISSUE THREAD

**Issue by Lucrezia-Cester** [GSTT-CSC/csc-test-site#123]
MONAI for Pathology:

MONAI for Pathology YouTube Video: [https://www.youtube.com/watch?v=Jy5VTqX4_jo](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg4rj02Zqnw&u=https%3a%2f%2fwww%2eyoutube%2ecom%2fwatch%3fv%3dJy5VTqX4%5fjo)

MONAI for Pathology Visions Poster: [https://docs.google.com/presentation/d/1nE1NnNynsb-ukaH_EL9hdrRm-BrW5d8r/edit?usp=sharing&ouid=111588075212775529445&rtpof=true&sd=true](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg4G_0DJrmQ&u=https%3a%2f%2fdocs%2egoogle%2ecom%2fpresentation%2fd%2f1nE1NnNynsb-ukaH%5fEL9hdrRm-BrW5d8r%2fedit%3fusp%3dsharing%26ouid%3d111588075212775529445%26rtpof%3dtrue%26sd%3dtrue)

MONAI for Pathology Medium Blog: [https://monai.medium.com/pathology-image-labeling-comes-to-monai-a033e200e587?source=friends_link&sk=01d75c9c3e7f4967db5a7b7e1ab1436a](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg4-zgTdqxA&u=https%3a%2f%2fmonai%2emedium%2ecom%2fpathology-image-labeling-comes-to-monai-a033e200e587%3fsource%3dfriends%5flink%26sk%3d01d75c9c3e7f4967db5a7b7e1ab1436a)

For easy sharing, here are Twitter/LinkedIn Posts for MONAI for Pathology Medium Blog:

Twitter: [https://twitter.com/ProjectMONAI/status/1536746618237530112](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg47ig2g4zA&u=https%3a%2f%2ftwitter%2ecom%2fProjectMONAI%2fstatus%2f1536746618237530112)
LinkedIn: [https://www.linkedin.com/posts/michaeljzephyr_pathology-image-labeling-comes-to-monai-activity-6942513125531250688-ezqe](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg92_02Q6ng&u=https%3a%2f%2fwww%2elinkedin%2ecom%2fposts%2fmichaeljzephyr%5fpathology-image-labeling-comes-to-monai-activity-6942513125531250688-ezqe)
 

MONAI Label Deep Dive Video Series:

MONAI YouTube Playlist: [https://www.youtube.com/playlist?list=PLtoSVSQ2XzyD4lc-lAacFBzOdv5Ou-9IA](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg4CwhmBqxA&u=https%3a%2f%2fwww%2eyoutube%2ecom%2fplaylist%3flist%3dPLtoSVSQ2XzyD4lc-lAacFBzOdv5Ou-9IA)

Videos covering MONAI Label + the following:

Installation
3D Slicer Module
Training from Scratch
Scribble Annotation
 

MONAI Releases:

MONAI Medium Blog for June/July releases: [https://monai.medium.com/4e0b6d8a11b5?source=friends_link&sk=570ec02d2d8799a116140a6420559b56](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg4C1gmBqyw&u=https%3a%2f%2fmonai%2emedium%2ecom%2f4e0b6d8a11b5%3fsource%3dfriends%5flink%26sk%3d570ec02d2d8799a116140a6420559b56)

MONAI Core v0.9
MONAI Label v0.4
MONAI Deploy App SDK v0.4
MONAI Informatics Gateway v0.2
For easy sharing, here are Twitter/LinkedIn Posts for MONAI Releases Medium Blog:

Twitter: [https://twitter.com/ProjectMONAI/status/1547297208310964224](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg9q3hmk6xA&u=https%3a%2f%2ftwitter%2ecom%2fProjectMONAI%2fstatus%2f1547297208310964224)
LinkedIn: [https://www.linkedin.com/posts/michaeljzephyr_monai-continues-its-pathology-integration-activity-6953066888817983488-9dqn](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg96xgWBozw&u=https%3a%2f%2fwww%2elinkedin%2ecom%2fposts%2fmichaeljzephyr%5fmonai-continues-its-pathology-integration-activity-6953066888817983488-9dqn%3futm%5fsource%3dlinkedin%5fshare%26utm%5fmedium%3dmember%5fdesktop%5fweb)
 

MONAI Events: Please promote these events in your network

Previous:

Project Week #37

Session Information: [https://github.com/NA-MIC/ProjectWeek/blob/master/PW37_2022_Virtual/MONAILabel_Workshop.md](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg4Gz12Fpyg&u=https%3a%2f%2fgithub%2ecom%2fNA-MIC%2fProjectWeek%2fblob%2fmaster%2fPW37%5f2022%5fVirtual%2fMONAILabel%5fWorkshop%2emd)
Recording: [https://www.youtube.com/watch?v=wtiEe_jiUzg](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg43k1DVszg&u=https%3a%2f%2fwww%2eyoutube%2ecom%2fwatch%3fv%3dwtiEe%5fjiUzg)
Future:

Post-MIDL MONAI Meetup (July 28th, 8 am – 11 am CET):  [https://monai.io/monai-meetup/](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg9yygzM4yQ&u=https%3a%2f%2fmonai%2eio%2fmonai-meetup%2f)

MONAI at MICCAI Tutorial (September 22nd, 8 am – 3 pm SGT): [https://monai.io/monai-tutorial-miccai-2022/](https://scanmail.trustwave.com/?c=8248&d=ipDP4iL033btVeLgv_uL2cBZv6O3dR5dg97kg2BtmQ&u=https%3a%2f%2fmonai%2eio%2fmonai-tutorial-miccai-2022%2f)

Post-MICCAI MONAI Event (Tentative): If you know anyone interested in presenting work at a future MONAI Meetup/Dev Day, please let me know.

GTC (Sept 19th – Sept 22nd):

MONAI Core DLI (Self-Supervised Learning and DiNTS)
MONAI Label DLI
MONAI Deploy DLI
MONAI and FLARE

**Comment by hshuaib90** [comment]
Closing as these are 2022 events
