### ISSUE TITLE
reading list

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/csc-test-site#131]
On the previous version of the website there used to be a reading list, this seems to be missing now. Can we add this back in or was there a reason it was dropped @tomaroberts ?

In the meantime, I'll compile a readlng list here:
- https://future.com/emerging-architectures-modern-data-infrastructure/
- https://machinelearningmastery.com/the-model-performance-mismatch-problem/
- https://chsasank.com/deep-learning-image-features.html
- https://github.com/EthicalML/awesome-production-machine-learning#neural-architecture-search
- https://www.mitre.org/sites/default/files/publications/Playbook-for-Threat-Modeling-Medical-Devices.pdf
- https://www.jacr.org/article/S1546-1440(20)31020-6/fulltext?mobileUi=0#secsectitle0025
- Presenting machine learning model information to clinical end users with model facts labels https://www.nature.com/articles/s41746-020-0253-3#Sec4
- https://link.springer.com/article/10.1007/s00330-020-07684-x
- https://assets.public.digital/Open_Source_Report.pdf
- https://www.health.org.uk/publications/reports/switched-on
- https://arxiv.org/pdf/2201.00650.pdf
- https://www.tandfonline.com/doi/pdf/10.1080/15265161.2021.2013977?needAccess=true
- https://lilianweng.github.io/posts/2021-07-11-diffusion-models/
- https://blog.qure.ai/notes/fluentd-logs
- https://www.cambridge.org/core/journals/journal-of-law-medicine-and-ethics/article/mitigating-racial-bias-in-machine-learning/325C9BF492331B16EFC154996BE0394F
- https://www.sciencedirect.com/science/article/pii/S2589750022000036#!
- https://ai.googleblog.com/2022/07/simplified-transfer-learning-for-chest.html
- https://pubs.rsna.org/doi/epdf/10.1148/radiol.212151
- https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-020-01224-9
- Model Evaluation, Model Selection, and Algorithm Selection in Machine Learning: https://arxiv.org/pdf/1811.12808.pdf
- Evaluating machine learning models and their diagnostic value: https://hal.inria.fr/hal-03682454/
- https://understandingpatientdata.org.uk/what-are-best-words-use-when-talking-about-data

**Comment by tomaroberts** [comment]
No reason for drop – must've been an oversight.

Separate page under About Us or section in Handbook?

**Comment by hshuaib90** [comment]
It was at the same level as 'Resources' before. Although I think both belong in the handbook (at least in terms of link/reference and the page can be separate).
