### ISSUE TITLE
communities

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/csc-test-site#132]
There should be a communities page , which should contain links to forums, blogs, mailing lists, newsletters etc. that are deemed to be useful. I'll start compiling a list here:

- IPEM https://my.community.ipem.ac.uk (particularly Clinical Scientific Computing
- OpenRegulatory https://openregulatory.com/community/
- Increment https://increment.com/issues/
- Shreya Shankar blog https://www.shreya-shankar.com
- NHSX Skunkworks https://nhsx.github.io/skunkworks
- NHS Python Community https://nhs-pycom.net

**Comment by laurencejackson** [comment]
- [MONAI community](https://monai.io/community.html), and [MONAI blog](https://monai.medium.com/)

**Comment by dangerdika** [comment]
@Lucrezia-Cester can you add Monai community & blog too?
