### ISSUE TITLE
Updates needed to staff page and calendar page

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/csc-test-site#151]
Lucy Funnell needs to be removed and the calendar needs to be updated

**Comment by AnilMistry** [comment]
Going forward should we maintain old member profiles or should they be fully removed?

I think articles and blog entries, authored by staff who then leave, should remain on the website.

**Comment by dangerdika** [comment]
I think remove them from the website's 'About Us' section but keep their writings on the website.
