### ISSUE TITLE
Scarlet badge link broken on projects page

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/csc-test-site#167]
When Viewing the projects pages the scarlet bade shown at the bottom of the page references the wrong location. 

Loading error:
![image](https://user-images.githubusercontent.com/33687657/212056672-faf2392a-4092-4454-9de1-bdc60face5a1.png)

The page attempts to load the badge from `/projects/assets/...` instead of `/assets/...`

![image](https://user-images.githubusercontent.com/33687657/212056871-13bcd171-4214-4d49-a154-022db93ceef8.png)

**Comment by AnilMistry** [comment]
#170 looks like it fixed this issue.
