### ISSUE TITLE
Guide on how to update the website should be updated and put to guides

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/csc-test-site#175]
The old website had a 'how to contribute to this website' guide which was useful for new starters - it should be updated to reflect the current practice and put under 'guides'

**Comment by heyhaleema** [comment]
@dangerdika Just to confirm, do you mean [this](https://github.com/GSTT-CSC/gstt-csc-old/blob/6415913c97f175e457e1ce999c301f37916c8ad3/howto.md) guide?

**Comment by dangerdika** [comment]
@heyhaleema yep - some of the setup is encapsulated in the readme but i really think it should be on the website
