### ISSUE TITLE
Automatically report repository activity with REST API

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/csc-test-site#178]
Currently we report repo/project activity manually. It would be good to have a script to automate this.

Using the GIthub REST API we can fetch a list of issues [reference](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues), this list can then be filtered to report the statistics we're interested in. 

The script should run on a schedule and output:
1. a csv or similar datastore that records the weekly activity for all given projects, this should be automatically backed up on repo, website or shared cloud storage.
2. a formatted table for copy/pasting into the meeting notes. 

Ideas for future enhancements:
- plot / visualise the activity statistics 
- Open PRs reporting the activity to the relevant pages on the website
- The

**Comment by dangerdika** [comment]
@mikewoodward94 youve worked on this, is it possible to implement or should this issue be closed?

**Comment by dangerdika** [comment]
The way we manage project updates has changed so this issue is no longer relevant
