### ISSUE TITLE
Create Blog > Articles page

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#18]
Issue to track creation of Blog Articles page.

NB: currently on the Miro board we only have a "Workshops" tab under this heading. Suggest we have both Blog>Articles and Blog>Workshops pages.

Can port across the old blog entried from here: https://gstt-csc.github.io/blog.html

Suggest having a more traditional blog type page, rather than a markdown table of links, i.e.: more like the posts layout here: https://mmistakes.github.io/so-simple-theme/

First new blog post can be introducing the new site!

**Comment by AnilMistry** [comment]
@tomaroberts 

Thanks for link, really useful. I'll base the structure around that. 

The blogs will be written in .md format so we can use liquid {content} to fill the templates. The README suggested these .md files should be stored in the home directory, but this could get messy. Shall i create a separate directory off main (eg /blogs/)  to containing the actual blogs content?

**Comment by tomaroberts** [comment]
Yeah, a /blogs/ folder would be great. I intend to have a similar folder structure for the team members page as currently they are all piling up in the root directory as well.
