### ISSUE TITLE
Update calendar and team staff page

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/csc-test-site#191]
- [x] remove Ryan from staff
- [x] remove past events from calendar
- [x] add new events to calendar

**Comment by hshuaib90** [comment]
Hi @dangerdika , when will you be able to get to this?

**Comment by dangerdika** [comment]
> Hi @dangerdika , when will you be able to get to this?

Aiming to get it done by the end of this week @hshuaib90!
