### ISSUE TITLE
Write Team Member bio pages

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#20]
We all need to write our Team Member bio entries, such as Lucy's: `lucy.html`

**To do list:**
- [x] Haris
- [x] Dika
- [x] Lucy
- [x] Simone
- [x] Laurence
- [x] Anil
- [x] Alex
- [x] Lu
- [x] Tom
- [x] Haleema
- [ ] Kavitha

**Comment by AnilMistry** [comment]
@tomaroberts Apologies, I forgot to create a new branch so my commit for updating my bio has automatically merged with the Main branch. I can role this back if required.

**Comment by dangerdika** [comment]
@GSTT-CSC/core I think this is quite hard to write for all, maybe we need some instruction on what should be in there?
Bio: describe professional journey only? Or put in general bio of where we studied and what jobs we've had? Or should we add things like hobbies or something to add a flare for who we are, or do we not do that? Do we add what we're hoping to develop, e.g. 'specific interest in promotion of equality and diversity in AI healtchare space'?
CSC Team role: Do we list our projects here and add links? Do we just broadly speak about past projects and current projects? Do we talk about interests?
A bit of fun questions at the bottom: did we decide to do these or not? Should we have a vote? 2 pages currently up, one with and one without. Whatever we choose, there should be symmetry.

Can we discuss this specifically and set out a skeleton structure for everyone to follow at next workshop @tomaroberts @lucy-funnell ?

**Comment by lucy-funnell** [comment]
Hi Dika,
Good points, 
I kept it quite short and sweet, I didn't want it to become like 'This is your life' a program from the 90's as it just a little introduction to each of us.
Bio: I suggested keeping the background to 50-60words about our current care path,studies, jobs but keeping it relevant (no one cares about GCSE's anymore right?). I like to idea of adding what we are hoping to develop. 
CSC Team role: This was just about the projects (past and present) and what we are developing in relation to people platforms and policies in the CSC Team. Adding what our unique contribution or interests are in is also a great idea.
We never reached a conclusion about the Fun Questions, I'm happy to revisit this in the workshop.

**Comment by hshuaib90** [comment]
I typically use something like the below. It's pretty straightforward. I think that's an easy starting point for the first iteration.

> Haris Shuaib is a Consultant Clinical Scientist and Head of the Clinical Scientific Computing section at Guy’s & St Thomas’ NHS Foundation Trust, where his team are developing people, platforms, and policy for digital health.
>  
> He is also the AI Transformation Lead at the London Medical Imaging & AI Centre for Value Based Healthcare where he oversees the development of AI prototypes across over 20 patient pathways in partnership with academia, industry and NHS Trusts. He is also the inventor and technical lead of the AI Deployment Engine, a platform which seeks to make integration of AI software into clinical pathways safe and efficient.
>  
> Finally, he also holds a NIHR Doctoral Research Fellowship, where he is leading a national multi-centre trial to see whether AI can improve the treatment of glioblastoma.

**Comment by tomaroberts** [comment]
Yep, I like Haris's bio – think that is a good style to go with.

**Comment by alexandertdeng** [comment]
#100

**Comment by tomaroberts** [comment]
Closing this – going to add Kavitha to a separate Issue. Thanks everyone.
