### ISSUE TITLE
create SOP for prepping cases for evaluation

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/csc-test-site#215]
As part of incidental PE AI evaluation, the radiologists provided some helpful suggestions in order to facilitate their role indouble reporting discrepant cases:

- Coping all attendance numbers / etc onto PACS - not sure if a list could be created on PACS, so we could just seamlessly move from one case to the other, allowing for appropriate numbering of the patients?
- Loading old archived studies – some of them are old, and they need to be uploaded from archive. Not sure if you or the PACS team could automatically unarchive them from PACS for us? Not sure how long they stay unarchived (?days), but that would save half the time we take to go through these! 

We should create a brief how-to guide for future cases that advises how we might prep cases to make for easier review.

**Comment by heyhaleema** [comment]
> * Coping all attendance numbers / etc onto PACS - not sure if a list could be created on PACS, so we could just seamlessly move from one case to the other, allowing for appropriate numbering of the patients?

@hshuaib90 Does the above mean mapping PACS order IDs e.g., accession numbers, to attendance IDs, and then flagging duplicates and discrepant records?

**Comment by dangerdika** [comment]
@aysha1207 is this issue still needed / do you have this information somewhere?

**Comment by dangerdika** [comment]
Information included in AI eval policy, closing the issue
