### ISSUE TITLE
Update Calendar 

### ISSUE THREAD

**Issue by AnilMistry** [GSTT-CSC/csc-test-site#224]
2 items on the calendar are currently out of date.

**Comment by sourav7274** [comment]
Hi, I am interested in contributing for this problem, could you describe the issue a little more please, eg. from where should I update and what should I update, and on which file

**Comment by AnilMistry** [comment]
Hi @sourav7274, in _data/calendar.yml there are items which are now out of date, these need to be removed.

**Comment by dangerdika** [comment]
Calendar updated for 2024
