### ISSUE TITLE
XNAT calculator does not properly display on Safari browser

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/csc-test-site#233]
Related to #229, the [XNAT calculator on the website](https://gstt-csc.github.io/platforms/xnat.html) does not properly display on the Safari browser i.e., it requests a Microsoft sign-in:

<img width="713" alt="image" src="https://github.com/GSTT-CSC/gstt-csc.github.io/assets/67117138/929b7608-b0d4-4dc4-a02d-302ddc901fe5">

This does properly display, however, on Mozilla, Brave, and Chrome browsers i.e., as a result of using an all-access embedded link.

**Comment by heyhaleema** [comment]
2023-09-24 - Calculator now seems to be broken on Brave, too:

<img width="788" alt="image" src="https://github.com/user-attachments/assets/73858fba-8462-4222-87ba-9296994d3e18">

@dangerdika My vote would be to take this out of the XNAT page until further notice and add a general explanation about our costing approach.

**Comment by dangerdika** [comment]
@heyhaleema I agree. removing it now.
