### ISSUE TITLE
Migrate AI4VBH FCAI to CSC People

### ISSUE THREAD

**Issue by Beatrix-Fletcher** [GSTT-CSC/csc-test-site#243]
Move all Fellowships in Clinical AI webpages from AI Centre website to CSC website

**Comment by Beatrix-Fletcher** [comment]
DONE 
- [x] Size and shape and add image to people buttons @hshuaib90 
- [x] Add Fellowship resources file to resources page - @hshuaib90 
- [x] Change Fellowship in nav link to new Fellowships Landing page @Beatrix-Fletcher 
- [x] Add info from get involved that this is not right spot for FCAI (direct to mailbox) @hshuaib90 
- [x] Remove CSCTeam@ link on website @Beatrix-Fletcher 
- [x] Fix fellowship buttons - @Beatrix-Fletcher 
- [x] Stylise all button pages directed from fellowship page @Beatrix-Fletcher 

MUST-HAVE before 8th 
- [x] Add email link to fellowships landing page @hshuaib90 
- [x] Add ‘supported by’ organisations to fellowships blurb @alexandertdeng 
- [x] Decomission AI4VBH website pages + LINK OUT TO NEW WEBSITE @alexandertdeng 
- [x] Add job role document to cohort 3 page @Beatrix-Fletcher 
- [x] Add FAQ text to cohort 3 page @alexandertdeng 
- [x] Add webinar link to cohort 3 page @Beatrix-Fletcher 
- [x] Add link to application form to pages @Beatrix-Fletcher 
- [x] CURRENT COHORT PAGE TEXT @alexandertdeng 
- [x] PREVIOUS COHORT PAGE TEXT @alexandertdeng 
- [x] Change wording to Fellowship not Fellowships @alexandertdeng @Beatrix-Fletcher 
- [x] Remove Email button in footer on about us (and anywhere else it is on website) @hshuaib90 
- [x] Move Nice to Haves to new issue @Beatrix-Fletcher

**Comment by hshuaib90** [comment]
@Beatrix-Fletcher can we split the above tasks into must-haves and nice-to-haves? And then maybe make a separate issue for the nice to haves that are not done yet? I think it would be good to get the fellowship stuff live asap. What do you think?

**Comment by Beatrix-Fletcher** [comment]
Sounds good, I will split them in the original to do list comment and once we agree on the split am happy to move the nice to haves to a new issue
