### ISSUE TITLE
Add El to Team

### ISSUE THREAD

**Issue by EStyli** [GSTT-CSC/csc-test-site#248]

**Comment by hshuaib90** [comment]
Hi @EStyli @AnilMistry ,the image aspect ratio still needs fixing :

![image](https://github.com/GSTT-CSC/gstt-csc.github.io/assets/19840489/981e5145-8185-4379-bf0d-9ec164d97901)

**Comment by EStyli** [comment]
Ratio adjusted, push/pulled already?
