### ISSUE TITLE
Improvements to CSC People Page 

### ISSUE THREAD

**Issue by Beatrix-Fletcher** [GSTT-CSC/csc-test-site#256]
Nice to Haves during Migration of AI4VBH Fellowship to CSC People

**Comment by Beatrix-Fletcher** [comment]
- [ ] Add borders/boxes around Fellowship Buttons
- [ ] ?change Fellowship buttons (forward, back, target)
- [ ] Create and add table to the sign-posting page 
- [ ] Make HIN Evaluation/Improvements Page 
- [ ] Add project list to cohort 3 page 
- [ ] Make HIN Evaluation/Improvements button from fellowships page
- [ ] Add sliders and images to previous and current cohorts 
- [x] Fellowships before STP in sub nav 
- [ ] ?Add Images of Fellows to Cohort 2 page 
- [ ] ?Add Images of Fellows to Cohort 1 page
- [x] Add curriculum to further general information page 
- [x] Cohort 1 selected outputs clickable URLs
- [ ] Archive fellow output links where possible to prevent linkrot
- [ ] Remove deadlinks on People landing page- Other programmes and Resources

**Comment by alexandertdeng** [comment]
Suggestion
- [ ] Merge Cohort 1 & Cohort 2 pages
- [ ] Rationalise naming of fellowship subpages

**Comment by alexandertdeng** [comment]
Please revert Open issue- checklist still incomplete

**Comment by alexandertdeng** [comment]
List above has been split into separate issues now.
