### ISSUE TITLE
Add graphic to show regions on Fellows landing page

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/csc-test-site#265]
At the moment the fellows landing page isnt super clear that it is a national programme. i think it would help to have a inforgraphic showing the regions that are included just as a rough visual to anchor people. Here's an example from a paper I wrote showing the sites we're recruiting from:
![image](https://github.com/GSTT-CSC/gstt-csc.github.io/assets/19840489/08ff430d-9cf2-4a6a-809b-b0bf062aed40)
What do you think @Beatrix-Fletcher @alexandertdeng ?

**Comment by alexandertdeng** [comment]
<img width="528" alt="Fellowship Regions C3" src="https://github.com/GSTT-CSC/gstt-csc.github.io/assets/86077069/f77df11a-f6d4-4612-a5fe-04a91170f09b">
Mockup

**Comment by hshuaib90** [comment]
Yes I think something like this would work. @Beatrix-Fletcher any thoughts? if we can outline the regions that would help with visual

**Comment by alexandertdeng** [comment]
<img width="670" alt="FCAI_Cohort3_map" src="https://github.com/GSTT-CSC/gstt-csc.github.io/assets/86077069/d96507cd-1ec3-4df4-b1ec-0b806f5d86e6">
Regions outlined

**Comment by alexandertdeng** [comment]
Suggest recruitment page is a better place for this to live as it directly pertains to recruitment of this cohort

**Comment by hshuaib90** [comment]
I think the problem we're trying to address though is that it's unclear on the landing page that this is a national programme. How do we make that clear?

**Comment by alexandertdeng** [comment]
Made some further edits for the hard of reading

**Comment by Beatrix-Fletcher** [comment]
I personally think the ideal situation would be that the landing page doesn't have as much text, just a very brief intro (see eg below). Background text is moved back to general/further info and the map of the regions is in Cohort 3 Applications. 

eg 

The Fellowship in Clinical AI is a year-long programme that is integrated part-time alongside clinical work. It is centrally managed by GSTT but runs in multiple regions across the UK. 

This unique programme is featured in the [NHS Long Term Workforce Plan](https://www.england.nhs.uk/publication/nhs-long-term-workforce-plan/) as an exemplar of upskilling staff to maximise the transformational benefit of AI technologies in the NHS.

Our fellows are smart and energetic individuals who will lead the charge to revolutionise clinical workflows with AI. Fellows are centrally recruited competitively from various clinical workforce groups across participating regions of the NHS, including medical and dental specialty trainees, nurses & midwives, AHPs, and pharmacy professionals.

Find out which regions are participating in Cohort 3 via the applications page below.

**Comment by Beatrix-Fletcher** [comment]
I also think we need to put some effort into making the Pervious Cohort and Current Cohort Pages more inviting and interesting - the Induction or Graduation pictures with them all together, the project cards as a slider or the quote slides. These will help with provoking thoughts like 'ahh there are Fellows in Midlands'

**Comment by hshuaib90** [comment]
> I also think we need to put some effort into making the Pervious Cohort and Current Cohort Pages more inviting and interesting - the Induction or Graduation pictures with them all together, the project cards as a slider or the quote slides. These will help with provoking thoughts like 'ahh there are Fellows in Midlands'

Yes I agree. Do we have a separate issue on this? If not do you mind creating one?

**Comment by Beatrix-Fletcher** [comment]
Sure, done.

**Comment by hshuaib90** [comment]
> Made some further edits for the hard of reading

Thanks @alexandertdeng . There's three separate branch for this issue. Are you able to merge them into one branch and delete the others? Or split it into multiple issues and assign one branch to each issue.

**Comment by alexandertdeng** [comment]
> > Made some further edits for the hard of reading
> 
> Thanks @alexandertdeng . There's three separate branch for this issue. Are you able to merge them into one branch and delete the others? Or split it into multiple issues and assign one branch to each issue.

I have split the landing page text update into a separate issue now. There are now two separate pull requests and linked to two separate issues
