### ISSUE TITLE
Jazz up Previous Cohort and Current Cohort Fellowship Pages 

### ISSUE THREAD

**Issue by Beatrix-Fletcher** [GSTT-CSC/csc-test-site#269]
effort into making the Pervious Cohort and Current Cohort Pages more inviting and interesting - the Induction or Graduation pictures with them all together, the project cards as a slider or the quote slides. These will help with provoking thoughts like 'ahh there are Fellows in Midlands'

**Comment by alexandertdeng** [comment]
Deleting as individual points for improvement now raised in other issues- twitter cards to be added in galleries.
