### ISSUE TITLE
Page for helpful development, productivity, and utility tools

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/csc-test-site#315]
It would be helpful to have a section on the website that lists development, productivity, and utility tools e.g., [Amphetamine](https://apps.apple.com/au/app/amphetamine/id937984704?mt=12) (a keep-awake app), [GitHub Desktop](https://desktop.github.com/) (Git GUI), [Notion templates](https://www.notion.so/templates), etc.

**Comment by dangerdika** [comment]
@heyhaleema are we happy to put these on the Notion under 'useful resources' with appropriate tag and therefore close this issue?
