### ISSUE TITLE
Add new content to People section

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#32]
Following Wed Workshop on 9th March, we pinned down the contents for the People section of the site. We decided we would have the following three subpages:

- **STP Scheme**
  - Details of training we provide [MVP for site launch]
  - Reference training that previous STPs have completed
  - Quotes from former STPs
  - Photos of alumni?
- **Clinical AI Fellowships**
  - @hshuaib90 said he would do this subpage
- **Get Involved**
  - Detail ways of working with us:
    - Internships
    - Secondments
    - STP Elective
    - Outreach / Taster days
    - Something broader to interest people who might want to work for CSC

**Comment by heyhaleema** [comment]
@hshuaib90 For the Fellowships section, should we link to or match [this page](https://www.aicentre.co.uk/fellowships)?

**Comment by hshuaib90** [comment]
I think link for now but create an issue that our page needs to be fleshed out

**Comment by tomaroberts** [comment]
Superseded by #69
