### ISSUE TITLE
Create Policy section

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#33]
Following Wed Workshop on 9th March, we discussed contents for Policy section. Decided upon two subheadings:

- Build Software
- Buy Software

Think we said we would effectively translate some of the material on the Shared Drive into these pages? Think you had a better idea of this than me @AnilMistry?

**Comment by tomaroberts** [comment]
Partially completed by #98

**Comment by hshuaib90** [comment]
@tomaroberts @AnilMistry this is complete right?

**Comment by tomaroberts** [comment]
It's technically done, as in the Buy/Build sections exist, and Anil has made a good start but I don't think the content is finished.

**Comment by hshuaib90** [comment]
OK great, will close this and then create specific issues to add to content
