### ISSUE TITLE
Add underline to hyperlink of current page

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#34]
Currently, not necessarily clear which subnav page you are on – request from Wed Workshop on 9th March to add underline to hyperlinks related to currently viewed page.

**Comment by tomaroberts** [comment]
Future reminder: I have been playing around with .active/.hover CSS elements in the Handbook branch and think there might be some CSS conflicts prevent links from 'appearing' active. This might also be an issue with the nav/subnav hyperlinks as well.

**Comment by hshuaib90** [comment]
![image](https://user-images.githubusercontent.com/19840489/218780824-bc6c68a7-4b02-4f5a-bcb4-c95b5d393239.png)
This works for the top nav and subnav.
