### ISSUE TITLE
Add trainee on-boarding section 

### ISSUE THREAD

**Issue by AnilMistry** [GSTT-CSC/csc-test-site#37]
This is a section for trainees/guests to consult before joining us so they know about our structure, working practcies and schedules, and what on boarding would look like for them.

It could also contain a link to the onboarding questionnaire where they can tell us about thier programming skills, aims, interests etc

- meet face to face
- local tour
- arrange 1-2-1s with team
- invite to meetings
- invite MT-CSC team
- primary and secondary supervisor nominated
- weekly 1-2-1 with primary supervisor

**Comment by tomaroberts** [comment]
This expands upon issue #32, specifically the Get Involved section.

**Comment by hshuaib90** [comment]
@AnilMistry are you able to work on this this week?

**Comment by hshuaib90** [comment]
On reflection, I would suggest this just be folded into the handbook. I don't think there should be a separate section as it creates potentially a lot of duplication. Can you have a look at what is missing from current handbook for trainees and create separate tickets for those? @AnilMistry

**Comment by AnilMistry** [comment]
At the moment potential trainee resources in the handbook are only provided in: 

- https://gstt-csc.github.io/handbook.html#Working-in-CSC/ for 10X
- https://gstt-csc.github.io/handbook.html#Standups/ for standups 
- Few parts of https://gstt-csc.github.io/handbook.html#Onboarding/ BH access and desks 

Onboarding section relates only to new permenant CSC starters, so not relevant for trainees:
https://gstt-csc.github.io/handbook.html#Onboarding/

I would argue for a separate section with links to these pages and a checklist of activities the trainees will conduct in the onboarding process. 

A revised list:

**Prospective applications**
Link to "Get Involved" section

**First week**
-  meet face-to-face - 1st day will meet CSC team member in person, guest sign in to becket house
- local tour (becket house 5th and 9th)
- arrange 1-2-1s with entire team - organised by trainee, 30 min meetings (within first 2 weeks)
- invite to meetings - 10X, standups, hackathons, interesting project meetings, conferences, QMS audits
- invite MT-CSC team - Haris to add newstarter to mailing list. 
- primary and secondary supervisor nominated - completed STP?
- weekly 1-2-1 with primary supervisor (secondary supervisor cc'd to step in if primary is absent)
- Get added to github 
- Scope out interesting projects
- Expectations of a blog post or two (links to previous trainee BP's)

**Experiences during placement**
A.I. project development 
Data extraction
Commercial AI deployment 
Conferences
QMS training and Audit
Expeirnece with MLops
Experience with GitHub 
Experience with XNAT
Access to Topol 


Adding pictures, make it seem interesting, advertising our opportunities and connections. 
Link this page to Get Involved section

**Comment by hshuaib90** [comment]
Thanks for this @AnilMistry . I think what you've proposed actually over 90% overlap with Onboarding of Core CSC members. The only thing I can see which is separate is primary/secondary supervisors. Why don't we amend the onboarding section and we can link to it from the Get Involved section? Let me know what you think

**Comment by AnilMistry** [comment]
Todays STP training evaluation meeting actions can be added too:


**Trainee 1 short rotation - Bioinformatics**

What can be improved:

- Schedules trainee time – weekly meetings
- Unclear when new staff start
- Unclear who was responsible for staff members

Actions:

- Identified the need for scheduled weekly checkup, so they know how to talk to
- Identify things the ***needed*** and things the ***wanted - map projects to ensure both are achieved***
- Identify specific persons to move projects/training along
- Organise 1-2-1's with all members on CSC
- Add schedule of when new starters join us, ensure training supervisor is assigned

**Trainee 2 – short rotation clinical engineer STP trainee**

What can be improved:

- Trainers were not as clear
- Ensure trainees feel as welcome as possible
- Trainer to confirm with trainee to what each learning experience covers
- Trainee does not know what amounts to **Completed** or **Done.**

Actions:

- Training supervisors to complete **Educator Training Resources (ETR) NEW > 01 - Supervision of Learner**s
- https://portal.e-lfh.org.uk/myElearning/Index?HierarchyId=0_54104_54116&programmeId=54104
- Trainees must work in ***Agile*** way, rather than **Waterfall.** See early draft of work, to get use to the idea of showing working (therefore understanding).
- Inclusion in all meetings attended by training supervisor for relevant projects, optional attendance by trainee as it fits with their schedule
- Competency mapped to timeline – flexible deadlines, prevent completing fake work.
- Identifying Trainee needs separate CSC needs.

**Trainee 3 – STP trainee MRI physicist** 

What can be improved:

- unclear trainee requirements at the start of rotation
- Required a mentor more than projects and competencies
- Confirming what trainee wanted – coding experience, and something tangible that impacts actual workload

Actions:

- Confirm trainee requirements at the start of rotation
- Confirm in what capacity trainees join, communicated with CSC team – trainee to reiterate this In 1-2-1's
- Example agenda for discussion in 1-2-1's
- Label GitHub Issues as STP appropriate (good first issue tag list) - got to repo and start with issues tagged with this.
- Don’t assign fake work. Reflected above ^^
