### ISSUE TITLE
STP: 2024 intake team pages

### ISSUE THREAD

**Issue by alexandertdeng** [GSTT-CSC/csc-test-site#434]
New STPs to create their own team pages for 'About Us' on CSC website.

**Comment by alexandertdeng** [comment]
@keriand please could you kindly add your new joiner colleagues and create a checklist for each member who needs to complete

- [x] Keri
- [x] David
- [ ] Kathan

**Comment by keriand** [comment]
> @keriand please could you kindly add your new joiner colleagues and create a checklist for each member who needs to complete
> 
> * [x]  Keri

No problem!

**Comment by ddemola** [comment]
Added my profile under a separate issue & PR #456, so Kathan can close this one once he's done.
