### ISSUE TITLE
Update content on Resources page

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#45]
The content on the Resources page hasn't been updated for a while and needs refreshing.

**Comment by heyhaleema** [comment]
Suggested additions:

- [NSHCS Scientist Training Programme (STP)](https://nshcs.hee.nhs.uk/programmes/stp/)
- [Public NHS Jobs site](https://www.jobs.nhs.uk/)
- [NHS Data Model and Dictionary for England](https://www.datadictionary.nhs.uk/)
- [NHS Python Community for Healthcare](https://nhs-pycom.net/)
- [DevDocs](https://devdocs.io/)
- [DataCamp](https://www.datacamp.com/)

I also suggest we keep [DeployStack](https://switowski.github.io/deploystack/) but mention that it is no longer being actively maintained.
