### ISSUE TITLE
Enhance content on People > Fellowships page

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/csc-test-site#56]
> I think link for now but create an issue that our page needs to be fleshed out
> 
> _Originally posted by @hshuaib90 in https://github.com/GSTT-CSC/csc-test-site/issues/32#issuecomment-1139515879_

Aside from link to AI Centre page [here](https://www.aicentre.co.uk/fellowships), add more content to People > Fellowships page, including other information specific to CSC, if any.

**Comment by heyhaleema** [comment]
Hi @alexandertdeng, tagging you in case you had any thoughts on what could/should go on this page.

**Comment by tomaroberts** [comment]
Resolved by #101
