### ISSUE TITLE
Verify accuracy of content in Get Involved page

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#69]
Related to Issues: #32 and #37

The Get Involved section is empty. From previous Issue:

- **Get Involved**
  - Detail ways of working with us:
    - Internships
    - Secondments
    - STP Elective
    - Outreach / Taster days
    - Something broader to interest people who might want to work for CSC

**Comment by heyhaleema** [comment]
@AnilMistry I've just added a few commits to the `update-getinvolved` branch and so once we're happy with our changes, we can go ahead and raise a PR to close both this issue and #60.

**Comment by tomaroberts** [comment]
Structure and content done – just need to verify content is accurate.

**Comment by hshuaib90** [comment]
Confirm this is accurate and closing issue
