### ISSUE TITLE
Include contact forms

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/csc-test-site#71]
It would be good to include [contact forms](https://getbootstrap.com/docs/5.2/forms/overview/) (particularly in the Get Involved and XNAT pages), but we will need to use something like [Formspree](https://formspree.io/), [Formkeep](https://formkeep.com/guides/contact-form-jekyll), [Formspark](https://formspark.io/), etc. to collect the submission data and have it emailed to, for example, the CSC team email (see [here](https://formkeep.com/guides/contact-form-jekyll) for information).

Also, for future development, it would be cool to add [reCAPTCHA](https://developers.google.com/recaptcha/intro), too.

**Comment by hshuaib90** [comment]
https://fabform.io/a/create-a-static-website-with-contact-form-on-github-pages some instructions I found

**Comment by hshuaib90** [comment]
@heyhaleema what are you thinking the purpose of the contact form is? A lot of our inbound messages come with attachments like a PID or data request or placement form etc. Would we want to allow people to upload files as well? Seems a bit dangerous.

**Comment by heyhaleema** [comment]
@hshuaib90 I was thinking of it being a way to standardise the format of requests submitted e.g., XNAT project requests, STP applications, etc., as well as to which mailbox they are delivered e.g., XNAT Admins, etc., to improve tracking and responses.

I'm in favour of having people to upload certain types of supporting files, but I wouldn't want anyone to upload anything particularly sensitive or private - which is why I'm still concerned about using [FabForm](https://fabform.io/), [Formspree](https://formspree.io/), etc. despite suggesting this!

Another alternative would be to have a Contact Us or Requests page where we list email addresses for certain requests and hyperlink these to trigger a simple email template?

**Comment by hshuaib90** [comment]
Sorry @heyhaleema for delay in coming back on this. I think this might be doable using Microsoft Forms, that allows file upload as well. I think it helps with some of the security issues. We can have a contact us page and links to either a superform or multiple forms. What do you think?

**Comment by heyhaleema** [comment]
@hshuaib90 No worries, thanks for the inspiration - I'm pro-superform! I've just made a start on draft PR #207 and I've been adding some comments there, too, on quirks I've run into with Microsoft Forms.
