### ISSUE TITLE
Platform names in browser tab not formatted correctly

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/csc-test-site#80]
The names of the platforms are formatted incorrectly in the browser tabs, e.g. "Mlops" should be "MLOps", "Aide" should be "AIDE", etc.

![image](https://user-images.githubusercontent.com/67117138/175296004-db32ac63-98b3-4f5a-b031-faf2476356d7.png)

We can manually correct this in the relevant HTML file, e.g. _site/platforms/aide.html, but it gets reset each time the site is built.

![image](https://user-images.githubusercontent.com/67117138/175296311-18f08797-3c5a-4602-ada8-cc707c2f7bb7.png)

**Comment by tomaroberts** [comment]
Dang... eagle eyes

**Comment by hshuaib90** [comment]
![image](https://user-images.githubusercontent.com/19840489/218869116-ea0acf43-f37d-409b-9b73-938008e8ee8d.png)
Solved
