### ISSUE TITLE
'our work' tab should be renamed to 'projects'

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/csc-test-site#84]
The current 'our work' tab contains _projects_, _resources_ and _roadmap_ . 

Roadmap is actually in About Us and redirects there. 

My argument is that resources should be in the handbook (because those are resources for us) and the tab should just be called 'projects' - it's the most interesting part, and separating people, platforms and policy away from 'our work' to me implies that we are part of a larger organisation where all we do are the projects and someone else is doing the rest.

Thoughts?

@GSTT-CSC/core

**Comment by tomaroberts** [comment]
> Roadmap is actually in About Us and redirects there.

This is a bug – easy to fix.

Agree with the wider sentiment. The Projects board is really important too, so deserving of its own tab I reckon.

**Comment by laurencejackson** [comment]
I agree with what @dangerdika says here, since the content under people, platforms, and policy are all actually "our work". Having the resources under the same tab as the handbook makes sense to me too.

**Comment by tomaroberts** [comment]
Ahh, I've just realised a snag. If we change Our Work > Projects, then the Projects tab will have no subnav entries because the Resources and Roadmap subnav links will be moved under About Us. Thus it will look like this:

![image](https://user-images.githubusercontent.com/15610752/176413871-076fa080-7a07-4dac-9082-938c9e4101ea.png)

Not the end of the world, but looks a little odd/different to rest of site. Thoughts?

**Comment by lucy-funnell** [comment]
In the future we could have 2 Sub tabs: Current, Previous/ Completed

**Comment by tomaroberts** [comment]
Oh yeah, that's a nice idea. I could change the subnav to say CURRENT PROJECTS:

![image](https://user-images.githubusercontent.com/15610752/176415727-f43db922-3624-412e-bd7f-912f09e043e0.png)

Then we add COMPLETED in the future?

**Comment by lucy-funnell** [comment]
I like it! 
Completed or Deployed. We could even add the Graveyard tab to project that haven't been successful and share the reasons why... V2.

**Comment by tomaroberts** [comment]
Resolved by #96
