### ISSUE TITLE
Interim AIDE and FLIP logos

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/csc-test-site#86]
As discussed in #81 we should put together some interim AIDE/FLIP logos. I'm creating a new issue for this so everyone can weigh in outside the context of #81.  

I've put together the two below as a starting point, could people let me know if they think these are along the right lines, or if they have any comments, or if I should try something else? 

![image](https://user-images.githubusercontent.com/33687657/175982539-70789f58-f756-47c0-8d85-7bab350d6762.png)

@GSTT-CSC/core

**Comment by heyhaleema** [comment]
I really like these, they look super clean. The only thing that comes to mind for potential change is could we have different colours for each of the right-hand bars in the FLIP logo, e.g. not just green?

**Comment by laurencejackson** [comment]
Thanks Haleema, tried adding some colours and made the lines a bit less chunky.

![image](https://user-images.githubusercontent.com/33687657/175994670-d0b0c0fa-2ce0-4a6e-8a89-7ce23202c900.png)

**Comment by laurencejackson** [comment]
and for AIDE too to keep the theme

![image](https://user-images.githubusercontent.com/33687657/175996457-31d9a5e6-2505-4464-ae37-6b93072db442.png)

**Comment by tomaroberts** [comment]
Right hand ones are my faves!

**Comment by heyhaleema** [comment]
Right-hand ones are my favourites, too, and I like the less chunky lines.

**Comment by hshuaib90** [comment]
Great starters. One edit would be to remove "AI deployment engine" from the logo name. AIDE should be generally stylised as AIDE alone. the fact that it stands for AI Deployment Engine is irrelevant from a visual or marketing perspective.

**Comment by hshuaib90** [comment]
Additionally, can we use the AI Centre colours ?

**Comment by laurencejackson** [comment]
Thanks @hshuaib90, removed the subtitles from both and tried AI colours with/without gradient. 

![image](https://user-images.githubusercontent.com/33687657/176181342-4f331759-030c-4014-8ff9-15e4608769cb.png)

**Comment by lloneill** [comment]
so good! have given @laurencejackson brand guidelines 😸

**Comment by laurencejackson** [comment]
Thanks to @lloneill, added the official colours and fonts and a few new options to post above.

**Comment by heyhaleema** [comment]
+1 for the bottom row!

**Comment by laurencejackson** [comment]
Sorry updated again, the bottom row has a different AI centre font - can be put on any of them if its preferred.

**Comment by AnilMistry** [comment]
Love the very bottom. unintentionally(?) stylised like the UKAS logo 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/79843755/176182794-178ee697-bdb2-447d-bf8a-490f49cef589.png">

**Comment by tomaroberts** [comment]
Niceeeee. I like the logos with gradient colour, and I like the font in the bottom row.

<img width="51" alt="image" src="https://user-images.githubusercontent.com/15610752/176195804-4971afd4-0fce-4dfd-81d3-59635507a664.png">

^^ I am slightly triggered by the different sized gaps between the rings. How does it look with equal gaps? Getting picky...

**Comment by lloneill** [comment]
we are all triggered by that dw

**Comment by lloneill** [comment]
Jorge likes the AIDE one and likes general vibe of FLIP but has suggested the FLIP one be star or triangle shaped, he gave this pic as a reference: 

![image](https://user-images.githubusercontent.com/106346436/176210268-d4a70493-668d-46eb-ae2b-1c30101eb2a0.jpg)

**Comment by alexandertdeng** [comment]
Some thoughts on 'legibility'- i.e. how recognisable and clear the logo is under different situations:

- Block colour rather than gradient makes logo more legible
- The rings on the AIDE logo are quite closely spaced- when small it is difficult to resolve different rings

**Comment by tomaroberts** [comment]
@laurencejackson 

I think we have finalised images now? Can we close this? Can you add replace the images on the website with the latest ones please.
